.TH "src/Object/Enemy/Boss/Boss.h" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Object/Enemy/Boss/Boss.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Enemy\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBoss\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBProjectileType\fP = \fBProjectile::ProjectileType\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBProjectile::ProjectileType\fP \fBProjectileType\fP = \fBProjectile::ProjectileType\fP"

.PP
Definition at line \fB3\fP of file \fBBoss\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
