.TH "src/Object/Enemy Directory Reference" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Object/Enemy Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAir\fP"
.br
.ti -1c
.RI "directory \fBBoss\fP"
.br
.ti -1c
.RI "directory \fBLand\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBEnemy\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEnemy\&.h\fP"
.br
.in -1c
