.TH "src/Entities Directory Reference" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Entities Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBEnemy\fP"
.br
.ti -1c
.RI "directory \fBInterfaces\fP"
.br
.ti -1c
.RI "directory \fBPlayer\fP"
.br
.ti -1c
.RI "directory \fBPowerUp\fP"
.br
.ti -1c
.RI "directory \fBProjectile\fP"
.br
.ti -1c
.RI "directory \fBTileEntity\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBEntity\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEntity\&.h\fP"
.br
.ti -1c
.RI "file \fBEntityData\&.h\fP"
.br
.in -1c
