.TH "src/Utility Directory Reference" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Utility Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBArray\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBEntityID\&.h\fP"
.br
.ti -1c
.RI "file \fBWindowSize\&.h\fP"
.br
.in -1c
