.TH "src/Object/Projectile Directory Reference" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Object/Projectile Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBExplosion\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBProjectile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBProjectile\&.h\fP"
.br
.in -1c
