.TH "src Directory Reference" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBEntities\fP"
.br
.ti -1c
.RI "directory \fBGame\fP"
.br
.ti -1c
.RI "directory \fBLevel\fP"
.br
.ti -1c
.RI "directory \fBObject\fP"
.br
.ti -1c
.RI "directory \fBSprites\fP"
.br
.ti -1c
.RI "directory \fBUtility\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBControllerStuff\&.hpp\fP"
.br
.ti -1c
.RI "file \fBMain\&.cpp\fP"
.br
.in -1c
