.TH "src/ControllerStuff.hpp" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ControllerStuff.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <SFML/Window\&.hpp>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBController\fP : unsigned char { \fBA\fP, \fBB\fP, \fBX\fP, \fBY\fP, \fBL2\fP, \fBR2\fP, \fBL1\fP, \fBR1\fP, \fBSelect_BTN\fP, \fBStart\fP, \fBL3\fP, \fBR3\fP, \fBD_Up\fP, \fBD_Down\fP, \fBD_Left\fP, \fBD_Right\fP }"
.br
.ti -1c
.RI "enum \fBControls\fP { \fBForward\fP, \fBLeft\fP, \fBBack\fP, \fBRight\fP, \fBShoot\fP, \fBSpecial\fP, \fBSpawn\fP, \fBFastForward\fP, \fBSelect\fP }"
.br
.ti -1c
.RI "enum \fBCountries\fP { \fBSTATES\fP, \fBJAPAN\fP, \fBSWEDEN\fP, \fBENGLAND\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBController\fP : unsigned char"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIA \fP
.TP
\f(BIB \fP
.TP
\f(BIX \fP
.TP
\f(BIY \fP
.TP
\f(BIL2 \fP
.TP
\f(BIR2 \fP
.TP
\f(BIL1 \fP
.TP
\f(BIR1 \fP
.TP
\f(BISelect_BTN \fP
.TP
\f(BIStart \fP
.TP
\f(BIL3 \fP
.TP
\f(BIR3 \fP
.TP
\f(BID_Up \fP
.TP
\f(BID_Down \fP
.TP
\f(BID_Left \fP
.TP
\f(BID_Right \fP
.PP
Definition at line \fB12\fP of file \fBControllerStuff\&.hpp\fP\&.
.SS "enum \fBControls\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIForward \fP
.TP
\f(BILeft \fP
.TP
\f(BIBack \fP
.TP
\f(BIRight \fP
.TP
\f(BIShoot \fP
.TP
\f(BISpecial \fP
.TP
\f(BISpawn \fP
.TP
\f(BIFastForward \fP
.TP
\f(BISelect \fP
.PP
Definition at line \fB32\fP of file \fBControllerStuff\&.hpp\fP\&.
.SS "enum \fBCountries\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BISTATES \fP
.TP
\f(BIJAPAN \fP
.TP
\f(BISWEDEN \fP
.TP
\f(BIENGLAND \fP
.PP
Definition at line \fB45\fP of file \fBControllerStuff\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
