.TH "Countdown" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Countdown
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Game\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "unsigned \fBgetTime\fP ()"
.br
.ti -1c
.RI "bool \fBisDone\fP ()"
.br
.ti -1c
.RI "void \fBtick\fP ()"
.br
.ti -1c
.RI "void \fBset\fP (unsigned seconds, unsigned ticksPerSec)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBGame\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned Countdown::getTime ()\fR [inline]\fP"

.PP
Definition at line \fB10\fP of file \fBGame\&.h\fP\&.
.SS "bool Countdown::isDone ()\fR [inline]\fP"

.PP
Definition at line \fB15\fP of file \fBGame\&.h\fP\&.
.SS "void Countdown::reset ()\fR [inline]\fP"

.PP
Definition at line \fB38\fP of file \fBGame\&.h\fP\&.
.SS "void Countdown::set (unsigned seconds, unsigned ticksPerSec)\fR [inline]\fP"

.PP
Definition at line \fB31\fP of file \fBGame\&.h\fP\&.
.SS "void Countdown::tick ()\fR [inline]\fP"

.PP
Definition at line \fB20\fP of file \fBGame\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
