.TH "src/Entities/Enemy/EnemyCollidable.h" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Entities/Enemy/EnemyCollidable.h
.SH SYNOPSIS
.br
.PP
\fR#include 'Enemy_new\&.h'\fP
.br
\fR#include '\&.\&./Interfaces/ICollidable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnemyCollidable\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
