.TH "src/Object/Enemy/Enemy.h" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Object/Enemy/Enemy.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Object\&.h'\fP
.br
\fR#include '\&.\&./Projectile/Projectile\&.h'\fP
.br
\fR#include '\&.\&./Projectile/Explosion/Explosion\&.h'\fP
.br
\fR#include '\&.\&./Collectable/Collectable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnemy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
