.TH "Entity::EntityHolder" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Entity::EntityHolder
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Entity\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBEntity\fP * > \fBenemies\fP"
.br
.ti -1c
.RI "std::vector< \fBEntity\fP * > \fBprojectiles\fP"
.br
.ti -1c
.RI "std::vector< \fBEntity\fP * > \fBother\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBEntity\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBEntity\fP*> Entity::EntityHolder::enemies"

.PP
Definition at line \fB17\fP of file \fBEntity\&.h\fP\&.
.SS "std::vector<\fBEntity\fP*> Entity::EntityHolder::other"

.PP
Definition at line \fB23\fP of file \fBEntity\&.h\fP\&.
.SS "std::vector<\fBEntity\fP*> Entity::EntityHolder::projectiles"

.PP
Definition at line \fB20\fP of file \fBEntity\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
