.TH "src/Entities/EntityData.h" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Entities/EntityData.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Utility/Array/StaticArray\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBEntityData::Cooldown\fP"
.br
.ti -1c
.RI "struct \fBEntityData::EntityData\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEntityData\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBcstr\fP = const char* const"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBStaticArray\fP< \fBEntityData\fP, static_cast< unsigned char >(\fBEntityID::COUNT\fP) > \fBEntityData::EntityDataTable\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBcstr\fP = const char* const"

.PP
Definition at line \fB4\fP of file \fBEntityData\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
