.TH "EntityData::EntityData" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EntityData::EntityData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <EntityData\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntityData\fP (\fBVec2f\fP \fBvelocity\fP, unsigned short \fBhealth\fP, \fBCooldown\fP \fBcooldown\fP, unsigned char \fBCHILD_DATA\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVec2f\fP \fBvelocity\fP"
.br
.ti -1c
.RI "unsigned short \fBhealth\fP"
.br
.ti -1c
.RI "\fBCooldown\fP \fBcooldown\fP"
.br
.ti -1c
.RI "const unsigned char \fBCHILD_DATA\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBEntityData\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EntityData::EntityData::EntityData (\fBVec2f\fP velocity, unsigned short health, \fBCooldown\fP cooldown, unsigned char CHILD_DATA)\fR [inline]\fP"

.PP
Definition at line \fB36\fP of file \fBEntityData\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const unsigned char EntityData::EntityData::CHILD_DATA"

.PP
Definition at line \fB34\fP of file \fBEntityData\&.h\fP\&.
.SS "\fBCooldown\fP EntityData::EntityData::cooldown"

.PP
Definition at line \fB30\fP of file \fBEntityData\&.h\fP\&.
.SS "unsigned short EntityData::EntityData::health"

.PP
Definition at line \fB28\fP of file \fBEntityData\&.h\fP\&.
.SS "\fBVec2f\fP EntityData::EntityData::velocity"

.PP
Definition at line \fB26\fP of file \fBEntityData\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
