.TH "src/Utility/EntityID.h" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Utility/EntityID.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBEntityTypeCounts\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBEntityID\fP : unsigned char { \fBENEMY_AIR_BABY_COPTER\fP = 0, \fBENEMY_AIR_BIG_PLANE\fP, \fBENEMY_AIR_SPINNY_PLANE\fP, \fBENEMY_AIR_CHILD_CHOPPER_BLADES\fP, \fBENEMY_LAND_TANK_WEAK\fP, \fBENEMY_LAND_TANK_STRONG\fP, \fBTILE_ROOFUS_ENGLAND\fP, \fBTILE_CONE_ENGLAND\fP, \fBTILE_HOUSE_ENGLAND\fP, \fBTILE_GATE_ENGLAND\fP, \fBTILE_HANGAR_ENGLAND\fP, \fBCOUNT\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBEntityID\fP : unsigned char\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIENEMY_AIR_BABY_COPTER \fP
.TP
\f(BIENEMY_AIR_BIG_PLANE \fP
.TP
\f(BIENEMY_AIR_SPINNY_PLANE \fP
.TP
\f(BIENEMY_AIR_CHILD_CHOPPER_BLADES \fP
.TP
\f(BIENEMY_LAND_TANK_WEAK \fP
.TP
\f(BIENEMY_LAND_TANK_STRONG \fP
.TP
\f(BITILE_ROOFUS_ENGLAND \fP
.TP
\f(BITILE_CONE_ENGLAND \fP
.TP
\f(BITILE_HOUSE_ENGLAND \fP
.TP
\f(BITILE_GATE_ENGLAND \fP
.TP
\f(BITILE_HANGAR_ENGLAND \fP
.TP
\f(BICOUNT \fP
.PP
Definition at line \fB4\fP of file \fBEntityID\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
