.TH "EntityData::Cooldown" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EntityData::Cooldown
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <EntityData\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCooldown\fP (const short \fBBaseCooldown\fP, short \fBCurrentCooldown\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBBaseCooldown\fP"
.br
.ti -1c
.RI "short \fBCurrentCooldown\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBEntityData\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EntityData::Cooldown::Cooldown (const short BaseCooldown, short CurrentCooldown)\fR [inline]\fP"

.PP
Definition at line \fB18\fP of file \fBEntityData\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "short EntityData::Cooldown::BaseCooldown"

.PP
Definition at line \fB13\fP of file \fBEntityData\&.h\fP\&.
.SS "short EntityData::Cooldown::CurrentCooldown"

.PP
Definition at line \fB16\fP of file \fBEntityData\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
