.TH "EntityData" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EntityData
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCooldown\fP"
.br
.ti -1c
.RI "struct \fBEntityData\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBStaticArray\fP< \fBEntityData\fP, static_cast< unsigned char >(\fBEntityID::COUNT\fP) > \fBEntityDataTable\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBStaticArray\fP< \fBEntityData\fP, static_cast<unsigned char>(\fBEntityID::COUNT\fP) > EntityData::EntityDataTable"
\fBInitial value:\fP
.nf
=
    {
        {
            EntityData {
                Vec2f {
                    0, 
                    0  
                },
                0, 
                Cooldown {
                    0, 
                    0  
                },
                0 
            } 
        }
    }
.PP
.fi

.PP
Definition at line \fB49\fP of file \fBEntityData\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
