.TH "src/Object/Projectile/Explosion/Explosion.h" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Object/Projectile/Explosion/Explosion.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Projectile\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExplosion\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
