.TH "Game" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game \- Big class that handles the whole game\&. It is created and ran once in \fBMain\&.cpp\fP\&. The main game loop runs here\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Game\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGame\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.RI "Runs the primary gameplay loop\&. "
.ti -1c
.RI "void \fBdrawMenu\fP ()"
.br
.RI "Draws the country select menu\&. "
.ti -1c
.RI "void \fBupdateMenu\fP ()"
.br
.RI "Updates the country select menu\&. "
.in -1c
.SH "Detailed Description"
.PP 
Big class that handles the whole game\&. It is created and ran once in \fBMain\&.cpp\fP\&. The main game loop runs here\&. 

@TODO@ Handle inter-object interactions here - Ricky 
.PP
Definition at line \fB60\fP of file \fBGame\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Game::Game ()"

.PP
Definition at line \fB4\fP of file \fBGame\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Game::drawMenu ()"

.PP
Draws the country select menu\&. 
.PP
Definition at line \fB177\fP of file \fBGame\&.cpp\fP\&.
.SS "void Game::run ()"

.PP
Runs the primary gameplay loop\&. 
.PP
Definition at line \fB58\fP of file \fBGame\&.cpp\fP\&.
.SS "void Game::updateMenu ()"

.PP
Updates the country select menu\&. 
.PP
Definition at line \fB213\fP of file \fBGame\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
