.TH "src/Game/Game.h" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Game/Game.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Level/Level\&.h'\fP
.br
\fR#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCountdown\fP"
.br
.ti -1c
.RI "class \fBGame\fP"
.br
.RI "Big class that handles the whole game\&. It is created and ran once in \fBMain\&.cpp\fP\&. The main game loop runs here\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
