.TH "src/Entities/Interfaces/ICollidable.h" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Entities/Interfaces/ICollidable.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Entity\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBICollidable\fP"
.br
.ti -1c
.RI "struct \fBICollidable::Vec2UC\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
