.TH "ICollidable" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ICollidable
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ICollidable\&.h>\fP
.PP
Inherited by \fBEnemyCollidable\fP, \fBPlayer\fP, \fBProjectile\fP, and \fBTileEntity\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVec2UC\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const bool \fBCollidesWith\fP (\fBEntity\fP &other) noexcept=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBVec2UC\fP \fBbounds\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBICollidable\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual const bool ICollidable::CollidesWith (\fBEntity\fP & other)\fR [inline]\fP, \fR [pure virtual]\fP, \fR [noexcept]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBVec2UC\fP ICollidable::bounds\fR [protected]\fP"

.PP
Definition at line \fB16\fP of file \fBICollidable\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
