.TH "ICollidable::Vec2UC" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ICollidable::Vec2UC
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ICollidable\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBx\fP"
.br
.ti -1c
.RI "unsigned char \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBICollidable\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char ICollidable::Vec2UC::x"

.PP
Definition at line \fB13\fP of file \fBICollidable\&.h\fP\&.
.SS "unsigned char ICollidable::Vec2UC::y"

.PP
Definition at line \fB13\fP of file \fBICollidable\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
