.TH "src/Entities/Interfaces/IHasHealth.h" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Entities/Interfaces/IHasHealth.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./EntityData\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIHasHealth\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
