.TH "IHasChildren" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IHasChildren
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <IHasChildren\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBChildren\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBIHasChildren\fP (\fBEntity\fP *\fBchildren\fP, unsigned char count) noexcept"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBChildren\fP \fBchildren\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBIHasChildren\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IHasChildren::IHasChildren (\fBEntity\fP * children, unsigned char count)\fR [inline]\fP, \fR [protected]\fP, \fR [noexcept]\fP"

.PP
Definition at line \fB10\fP of file \fBIHasChildren\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBChildren\fP IHasChildren::children\fR [protected]\fP"

.PP
Definition at line \fB38\fP of file \fBIHasChildren\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
