.TH "IHasChildren::Children" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IHasChildren::Children
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <IHasChildren\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtick\fP ()"
.br
.ti -1c
.RI "\fB~Children\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEntity\fP * \fBchild\fP = nullptr"
.br
.ti -1c
.RI "unsigned char \fBcount\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBIHasChildren\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IHasChildren::Children::~Children ()\fR [inline]\fP"

.PP
Definition at line \fB31\fP of file \fBIHasChildren\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void IHasChildren::Children::tick ()\fR [inline]\fP"

.PP
Definition at line \fB23\fP of file \fBIHasChildren\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEntity\fP* IHasChildren::Children::child = nullptr"

.PP
Definition at line \fB18\fP of file \fBIHasChildren\&.h\fP\&.
.SS "unsigned char IHasChildren::Children::count = 0"

.PP
Definition at line \fB21\fP of file \fBIHasChildren\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
