.TH "IHasHealth" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IHasHealth
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <IHasHealth\&.h>\fP
.PP
Inherited by \fBEnemy\fP\fR [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "unsigned short \fBgetHealth\fP () const noexcept"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBIHasHealth\fP (\fBEntityID\fP ID)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBhealth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBIHasHealth\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IHasHealth::IHasHealth (\fBEntityID\fP ID)\fR [inline]\fP, \fR [protected]\fP"

.PP
Definition at line \fB13\fP of file \fBIHasHealth\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned short IHasHealth::getHealth () const\fR [inline]\fP, \fR [noexcept]\fP"

.PP
Definition at line \fB7\fP of file \fBIHasHealth\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned short IHasHealth::health\fR [protected]\fP"

.PP
Definition at line \fB16\fP of file \fBIHasHealth\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
