.TH "src/Level/Level.h" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Level/Level.h
.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include <SFML/Graphics\&.hpp>\fP
.br
\fR#include <climits>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include '\&.\&./Object/Enemy/Boss/Boss\&.h'\fP
.br
\fR#include '\&.\&./Object/Enemy/Air/Air\&.h'\fP
.br
\fR#include '\&.\&./Object/Enemy/Land/Land\&.h'\fP
.br
\fR#include '\&.\&./Object/Player/Player\&.h'\fP
.br
\fR#include '\&.\&./Object/Projectile/Projectile\&.h'\fP
.br
\fR#include '\&.\&./Object/Collectable/Collectable\&.h'\fP
.br
\fR#include '\&.\&./ControllerStuff\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLevel\fP"
.br
.RI "This takes a file and interprets it to create the level\&. ALL objects in a level are held here\&. UIs, menus, and things that span through multiple levels are held by \fBGame\fP\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHP_MAX\fP   SHRT_MAX"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HP_MAX   SHRT_MAX"

.PP
Definition at line \fB18\fP of file \fBLevel\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
