.TH "src/Main.cpp" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Game/Game\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line \fB26\fP of file \fBMain\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
