.TH "src/Object/Object.h" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Object/Object.h
.SH SYNOPSIS
.br
.PP
\fR#include <SFML/Graphics\&.hpp>\fP
.br
\fR#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBObject\fP"
.br
.RI "The base class for everything that moves\&. Making this allows us to use polymorphism to handle and run through every object in the game in a little neater manner\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
