.TH "sprites::SpriteData" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sprites::SpriteData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SpriteType\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBSpriteData\fP (\fBcstr\fP \fBfilename\fP, const \fBVec2f\fP \fBsize\fP, const unsigned char \fBanimationFrameCount\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "constexpr \fBcstr\fP \fBfilename\fP"
.br
.ti -1c
.RI "constexpr \fBVec2f\fP \fBsize\fP"
.br
.ti -1c
.RI "constexpr unsigned char \fBanimationFrameCount\fP"
.br
.ti -1c
.RI "unsigned char \fBcurrentFrame\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBSpriteType\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sprites::SpriteData::SpriteData (\fBcstr\fP filename, const \fBVec2f\fP size, const unsigned char animationFrameCount)\fR [inline]\fP, \fR [constexpr]\fP"

.PP
Definition at line \fB21\fP of file \fBSpriteType\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char sprites::SpriteData::animationFrameCount\fR [constexpr]\fP"

.PP
Definition at line \fB17\fP of file \fBSpriteType\&.h\fP\&.
.SS "unsigned char sprites::SpriteData::currentFrame = 0"

.PP
Definition at line \fB18\fP of file \fBSpriteType\&.h\fP\&.
.SS "\fBcstr\fP sprites::SpriteData::filename\fR [constexpr]\fP"

.PP
Definition at line \fB15\fP of file \fBSpriteType\&.h\fP\&.
.SS "\fBVec2f\fP sprites::SpriteData::size\fR [constexpr]\fP"

.PP
Definition at line \fB16\fP of file \fBSpriteType\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
