.TH "StaticArray< RAW_TYPE, LENGTH >::ReturnData" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StaticArray< RAW_TYPE, LENGTH >::ReturnData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <StaticArray\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReturnData\fP ()=delete"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const RAW_TYPE & \fBDATA\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename RAW_TYPE, unsigned char LENGTH>
.br
struct StaticArray< RAW_TYPE, LENGTH >::ReturnData"Holds the data returned when you access the array\&. Not constructed as a compile-time constant since it is constructed at runtime\&. 
.PP
Definition at line \fB23\fP of file \fBStaticArray\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename RAW_TYPE , unsigned char LENGTH> \fBStaticArray\fP< RAW_TYPE, LENGTH >::ReturnData::ReturnData ()\fR [delete]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename RAW_TYPE , unsigned char LENGTH> const RAW_TYPE& \fBStaticArray\fP< RAW_TYPE, LENGTH >::ReturnData::DATA"

.PP
Definition at line \fB26\fP of file \fBStaticArray\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
