.TH "VariableArray< RAW_TYPE, TOTAL_ELEMENTS, TOTAL_UNIQUE_OBJECTS >::SpacingElement" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VariableArray< RAW_TYPE, TOTAL_ELEMENTS, TOTAL_UNIQUE_OBJECTS >::SpacingElement
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <VariableArray\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBSpacingElement\fP (unsigned char \fBSTARTING_INDEX\fP, unsigned char \fBENDING_INDEX\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBSTARTING_INDEX\fP"
.br
.ti -1c
.RI "unsigned char \fBENDING_INDEX\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename RAW_TYPE, unsigned char TOTAL_ELEMENTS, unsigned char TOTAL_UNIQUE_OBJECTS>
.br
struct VariableArray< RAW_TYPE, TOTAL_ELEMENTS, TOTAL_UNIQUE_OBJECTS >::SpacingElement"Holds spacing information for a given element\&.

.PP
\fBWarning\fP
.RS 4
Can only be initialized as a compile-time constant\&. 
.RE
.PP

.PP
Definition at line \fB27\fP of file \fBVariableArray\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename RAW_TYPE , unsigned char TOTAL_ELEMENTS, unsigned char TOTAL_UNIQUE_OBJECTS> \fBVariableArray\fP< RAW_TYPE, TOTAL_ELEMENTS, TOTAL_UNIQUE_OBJECTS >::SpacingElement::SpacingElement (unsigned char STARTING_INDEX, unsigned char ENDING_INDEX)\fR [inline]\fP, \fR [constexpr]\fP"

.PP
\fBParameters\fP
.RS 4
\fISTARTING_INDEX\fP The index in the array where this element begins\&. 
.br
\fIENDING_INDEX\fP The index in the array where this element ends\&.
.RE
.PP
\fBWarning\fP
.RS 4
Can only be initialized as a compile-time constant\&. 
.RE
.PP

.PP
Definition at line \fB41\fP of file \fBVariableArray\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename RAW_TYPE , unsigned char TOTAL_ELEMENTS, unsigned char TOTAL_UNIQUE_OBJECTS> unsigned char \fBVariableArray\fP< RAW_TYPE, TOTAL_ELEMENTS, TOTAL_UNIQUE_OBJECTS >::SpacingElement::ENDING_INDEX"

.PP
Definition at line \fB32\fP of file \fBVariableArray\&.h\fP\&.
.SS "template<typename RAW_TYPE , unsigned char TOTAL_ELEMENTS, unsigned char TOTAL_UNIQUE_OBJECTS> unsigned char \fBVariableArray\fP< RAW_TYPE, TOTAL_ELEMENTS, TOTAL_UNIQUE_OBJECTS >::SpacingElement::STARTING_INDEX"

.PP
Definition at line \fB30\fP of file \fBVariableArray\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
