.TH "VariableArray< RAW_TYPE, TOTAL_ELEMENTS, TOTAL_UNIQUE_OBJECTS >::ReturnData" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VariableArray< RAW_TYPE, TOTAL_ELEMENTS, TOTAL_UNIQUE_OBJECTS >::ReturnData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <VariableArray\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReturnData\fP ()=delete"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const RAW_TYPE * \fBDATA\fP"
.br
.ti -1c
.RI "const unsigned char \fBCOUNT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename RAW_TYPE, unsigned char TOTAL_ELEMENTS, unsigned char TOTAL_UNIQUE_OBJECTS>
.br
struct VariableArray< RAW_TYPE, TOTAL_ELEMENTS, TOTAL_UNIQUE_OBJECTS >::ReturnData"Holds the data returned when you access the array\&. Not constructed as a compile-time constant since it is constructed at runtime\&. 
.PP
Definition at line \fB51\fP of file \fBVariableArray\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename RAW_TYPE , unsigned char TOTAL_ELEMENTS, unsigned char TOTAL_UNIQUE_OBJECTS> \fBVariableArray\fP< RAW_TYPE, TOTAL_ELEMENTS, TOTAL_UNIQUE_OBJECTS >::ReturnData::ReturnData ()\fR [delete]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename RAW_TYPE , unsigned char TOTAL_ELEMENTS, unsigned char TOTAL_UNIQUE_OBJECTS> const unsigned char \fBVariableArray\fP< RAW_TYPE, TOTAL_ELEMENTS, TOTAL_UNIQUE_OBJECTS >::ReturnData::COUNT"

.PP
Definition at line \fB56\fP of file \fBVariableArray\&.h\fP\&.
.SS "template<typename RAW_TYPE , unsigned char TOTAL_ELEMENTS, unsigned char TOTAL_UNIQUE_OBJECTS> const RAW_TYPE* \fBVariableArray\fP< RAW_TYPE, TOTAL_ELEMENTS, TOTAL_UNIQUE_OBJECTS >::ReturnData::DATA"

.PP
Definition at line \fB54\fP of file \fBVariableArray\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
