.TH "WindowSize" 3 "Version v0.1" "Aero Fighters" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowSize
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <WindowSize\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBwidth\fP"
.br
.ti -1c
.RI "unsigned short \fBheight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBWindowSize\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned short WindowSize::height"

.PP
Definition at line \fB10\fP of file \fBWindowSize\&.h\fP\&.
.SS "unsigned short WindowSize::width"

.PP
Definition at line \fB7\fP of file \fBWindowSize\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aero Fighters from the source code\&.
